version: '3'
services:
  node:
    tty: true
    stdin_open: true
    container_name: nest-template
    env_file:
      - ./.env
    depends_on:
      - mongo
    build:
      context: .
    ports:
      - 5050:5050
      - 9229:9229
    volumes:
      - .:/var/code:rw
    command: >
      bash -c "npm install
      && cp .env.example .env
      && npm run start:dev
      "
    links:
      - mongo

  mongo:
    image: 'mongo:3.4'
    logging:
      driver: 'none'
